[project]
name = "ticketflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tanisha1259", email = "tanishaprakash259@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "dspy>=3.3.1",
]

[project.scripts]
ticketflow = "ticketflow:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
